/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Material = IDL.Record({
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Project = IDL.Record({
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'completion_percentage' : IDL.Nat,
  'description' : IDL.Text,
  'instructions' : IDL.Text,
  'time_spent_minutes' : IDL.Nat,
  'materials' : IDL.Vec(Material),
  'images' : IDL.Vec(ExternalBlob),
});
export const Tutorial = IDL.Record({
  'title' : IDL.Text,
  'difficulty' : IDL.Text,
  'description' : IDL.Text,
  'steps' : IDL.Vec(IDL.Text),
  'materials' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({ 'bio' : IDL.Text, 'name' : IDL.Text });
export const CrochetPattern = IDL.Record({
  'pattern_steps' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'materials_needed' : IDL.Vec(Material),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPattern' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(Material)],
      [],
      [],
    ),
  'addProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(ExternalBlob), IDL.Vec(Material)],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTutorial' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'deleteTutorial' : IDL.Func([IDL.Text], [], []),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getAllTutorials' : IDL.Func([], [IDL.Vec(Tutorial)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPattern' : IDL.Func([IDL.Text], [IDL.Opt(CrochetPattern)], ['query']),
  'getPatterns' : IDL.Func([], [IDL.Vec(CrochetPattern)], ['query']),
  'getProjectMaterials' : IDL.Func([IDL.Text], [IDL.Vec(Material)], ['query']),
  'getProjects' : IDL.Func([IDL.Principal], [IDL.Vec(Project)], ['query']),
  'getTutorial' : IDL.Func([IDL.Text], [IDL.Opt(Tutorial)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeDefaultTutorials' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateProject' : IDL.Func(
      [IDL.Text, IDL.Vec(ExternalBlob), IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'updateTutorial' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Material = IDL.Record({
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Project = IDL.Record({
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'completion_percentage' : IDL.Nat,
    'description' : IDL.Text,
    'instructions' : IDL.Text,
    'time_spent_minutes' : IDL.Nat,
    'materials' : IDL.Vec(Material),
    'images' : IDL.Vec(ExternalBlob),
  });
  const Tutorial = IDL.Record({
    'title' : IDL.Text,
    'difficulty' : IDL.Text,
    'description' : IDL.Text,
    'steps' : IDL.Vec(IDL.Text),
    'materials' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'bio' : IDL.Text, 'name' : IDL.Text });
  const CrochetPattern = IDL.Record({
    'pattern_steps' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'materials_needed' : IDL.Vec(Material),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPattern' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(Material)],
        [],
        [],
      ),
    'addProject' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(ExternalBlob),
          IDL.Vec(Material),
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTutorial' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'deleteTutorial' : IDL.Func([IDL.Text], [], []),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getAllTutorials' : IDL.Func([], [IDL.Vec(Tutorial)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPattern' : IDL.Func([IDL.Text], [IDL.Opt(CrochetPattern)], ['query']),
    'getPatterns' : IDL.Func([], [IDL.Vec(CrochetPattern)], ['query']),
    'getProjectMaterials' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Material)],
        ['query'],
      ),
    'getProjects' : IDL.Func([IDL.Principal], [IDL.Vec(Project)], ['query']),
    'getTutorial' : IDL.Func([IDL.Text], [IDL.Opt(Tutorial)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeDefaultTutorials' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateProject' : IDL.Func(
        [IDL.Text, IDL.Vec(ExternalBlob), IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'updateTutorial' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };